/**
 * Created by linhaifeng on 2016/11/15.
 */

/*
* 
* 首页
* */
export const INDEX_GET_LIST_SUCCESS = 'INDEX_GET_LIST_SUCCESS';
export const INDEX_GET_IMG_SUCCESS = 'INDEX_GET_IMG_SUCCESS';

/*
* 
* 公共
* */
export const COMM_LOADING_SHOW = 'COMM_LOADING_SHOW';
export const COMM_LOADING_HIDDEN = 'COMM_LOADING_HIDDEN';
export const COMM_CONF = 'COMM_CONF';

/*
* 
* 文章页
* */

export const ARTICLE_GET_CONTENT = 'ARTICLE_GET_CONTENT';
export const ARTICLE_REPLY_STATUS = 'ARTICLE_REPLY_STATUS';
export const ARTICLE_SUBMIT_COMMENT = 'ARTICLE_SUBMIT_COMMENT';
export const ARTICLE_SUBMIT_REPLY = 'ARTICLE_SUBMIT_REPLY';
export const ARTICLE_SET_REPLY = 'ARTICLE_SUBMIT_REPLY'