/**
 * Created by linhaifeng on 2016/11/15.
 */

/*
* 
* 首页
* */
export const INDEX_GET_LIST_SUCCESS = 'INDEX_GET_LIST_SUCCESS';
export const INDEX_GET_IMG_SUCCESS = 'INDEX_GET_IMG_SUCCESS';

/*
* 
* 公共
* */
export const COMM_LOADING_STATUS = 'COMM_LOADING_STATUS';
export const COMM_CONF = 'COMM_CONF';
export const COMM_MARK_STATUS = 'COMM_MARK_STATUS';

/*
* 
* 文章
* */

export const ARTICLE_GET_CONTENT = 'ARTICLE_GET_CONTENT';
export const ARTICLE_REPLY_STATUS = 'ARTICLE_REPLY_STATUS';
export const ARTICLE_SUBMIT_COMMENT = 'ARTICLE_SUBMIT_COMMENT';
export const ARTICLE_SUBMIT_REPLY = 'ARTICLE_SUBMIT_REPLY';
export const ARTICLE_SET_REPLY = 'ARTICLE_SUBMIT_REPLY';

/*
*
* 日期选择
* */
export const CALENDAR_STATUS = 'CALENDAR_STATUS';
export const CALENDAR_GET_DATE = 'CALENDAR_GET_DATE';
export const CALENDAR_DATE_STATUS = 'CALENDAR_DATE_STATUS';
export const CALENDAR_CHOICE = 'CALENDAR_CHOICE';

/*
*
* 个人信息
* */
export const HOME_GET_INFO = "HOME_GET_INFO"